# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

JTinf <- function(nodesDf, edgesDf, evidenceDf_mRNA, genes) {
    .Call(`_CRNA_JTinf`, nodesDf, edgesDf, evidenceDf_mRNA, genes)
}

